### ISSUE TITLE
本番直前SP

### ISSUE THREAD

**Issue by cureseven** [cureseven/isucon-practice-20231123#1]
# ISUCON9本選

- [当日マニュアル](https://github.com/isucon/isucon9-final/blob/master/docs/MANUAL.md)
- [アプリケーションマニュアル](https://github.com/isucon/isucon9-final/blob/master/docs/webapp_spec.md)
- [API仕様書](https://github.com/isucon/isucon9-final/blob/master/docs/payment_spec.md)
- [github repository](https://github.com/isucon/isucon9-final)
- [チェックシート](https://www.notion.so/2023-9final-130134392a444ef3b5e307fa65bc8427?pvs=4)

t3.largeが近い

**Comment by mism-mism** [comment]
![image](https://github.com/cureseven/isucon-practice-20231123/assets/7067138/002084c9-3e20-403d-80e3-93cc2547ef62)

**Comment by cureseven** [comment]
goモジュールのversion依存がうまく噛み合ってなくて初期実装のbuildができなかった
最終練習日なので切り上げるよ

**Comment by cureseven** [comment]
こちらでISUCON12予選をやります
https://github.com/cureseven/isucon-practice-20231123-2
